# Pre-commit hooks configuration
# See https://pre-commit.com for more information

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: end-of-file-fixer
      - id: check-yaml
        args: [--allow-multiple-documents]
      - id: check-json
      - id: check-added-large-files
        args: [--maxkb=5000]
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: detect-private-key

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.56.0
    hooks:
      - id: eslint
        files: \.(js|ts|tsx|vue)$
        types: [file]
        args: [--fix, --max-warnings=0]
        additional_dependencies:
          - eslint@8.51.0

  - repo: local
    hooks:
      - id: vitest-related
        name: Run related tests
        entry: npm run test:related
        language: system
        files: \.(ts|tsx|vue)$
        pass_filenames: false
        stages: [commit]

      - id: type-check
        name: TypeScript type check
        entry: npm run type-check
        language: system
        files: \.(ts|tsx|vue)$
        pass_filenames: false
        stages: [commit]

default_stages: [commit]
