apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-web
spec:
  selector:
    matchLabels:
      run: nginx-web
  template:
    metadata:
      labels:
        run: nginx-web
    spec:
      containers:
        - name: nginx-web
          image: nginx:alpine
          ports:
            - containerPort: 443
              name: https-web-svc
            - containerPort: 80
              name: http-web-svc
          resources:
            limits:
              cpu: 500m
            requests:
              cpu: 200m
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-web
  labels:
    run: nginx-web
spec:
  ports:
    - name: http-web-svc
      protocol: TCP
      port: 80
      targetPort: http-web-svc
    - name: https-web-svc
      protocol: TCP
      port: 443
      targetPort: https-web-svc
  selector:
    run: nginx-web
