apiVersion: apps/v1
kind: Deployment
metadata:
  name: aviatrix-operator
  namespace: aviatrix-system
  labels:
    app.kubernetes.io/name: aviatrix-operator
    app.kubernetes.io/instance: aviatrix-operator
    app.kubernetes.io/component: controller
    app.kubernetes.io/created-by: aviatrix-operator
    app.kubernetes.io/part-of: aviatrix-operator
    app.kubernetes.io/managed-by: kustomize
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: aviatrix-operator
      app.kubernetes.io/instance: aviatrix-operator
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: aviatrix-operator
        app.kubernetes.io/instance: aviatrix-operator
    spec:
      serviceAccountName: aviatrix-operator
      containers:
        - name: manager
          image: aviatrix-operator:latest
          command:
            - /manager
          args:
            - --leader-elect
            - --aviatrix-controller-ip=$(AVIATRIX_CONTROLLER_IP)
            - --aviatrix-username=$(AVIATRIX_USERNAME)
            - --aviatrix-password=$(AVIATRIX_PASSWORD)
          env:
            - name: AVIATRIX_CONTROLLER_IP
              valueFrom:
                secretKeyRef:
                  name: aviatrix-controller-secret
                  key: controller-ip
            - name: AVIATRIX_USERNAME
              valueFrom:
                secretKeyRef:
                  name: aviatrix-controller-secret
                  key: username
            - name: AVIATRIX_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: aviatrix-controller-secret
                  key: password
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            limits:
              cpu: 500m
              memory: 128Mi
            requests:
              cpu: 10m
              memory: 64Mi
      terminationGracePeriodSeconds: 10
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: aviatrix-operator
  namespace: aviatrix-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: aviatrix-operator-manager-role
rules:
  - apiGroups: [""]
    resources: ["secrets", "configmaps"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["aviatrix.k8s.io"]
    resources: ["aviatrixcontrollers"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["aviatrix.k8s.io"]
    resources: ["aviatrixcontrollers/status"]
    verbs: ["get", "update", "patch"]
  - apiGroups: ["aviatrix.k8s.io"]
    resources: ["aviatrixcontrollers/finalizers"]
    verbs: ["update"]
  - apiGroups: ["aviatrix.k8s.io"]
    resources: ["aviatrixgateways"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["aviatrix.k8s.io"]
    resources: ["aviatrixgateways/status"]
    verbs: ["get", "update", "patch"]
  - apiGroups: ["aviatrix.k8s.io"]
    resources: ["aviatrixgateways/finalizers"]
    verbs: ["update"]
  - apiGroups: ["aviatrix.k8s.io"]
    resources: ["aviatrixspokegateways"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["aviatrix.k8s.io"]
    resources: ["aviatrixspokegateways/status"]
    verbs: ["get", "update", "patch"]
  - apiGroups: ["aviatrix.k8s.io"]
    resources: ["aviatrixspokegateways/finalizers"]
    verbs: ["update"]
  - apiGroups: ["aviatrix.k8s.io"]
    resources: ["aviatrixtransitgateways"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["aviatrix.k8s.io"]
    resources: ["aviatrixtransitgateways/status"]
    verbs: ["get", "update", "patch"]
  - apiGroups: ["aviatrix.k8s.io"]
    resources: ["aviatrixtransitgateways/finalizers"]
    verbs: ["update"]
  - apiGroups: ["aviatrix.k8s.io"]
    resources: ["aviatrixvpcs"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["aviatrix.k8s.io"]
    resources: ["aviatrixvpcs/status"]
    verbs: ["get", "update", "patch"]
  - apiGroups: ["aviatrix.k8s.io"]
    resources: ["aviatrixvpcs/finalizers"]
    verbs: ["update"]
  - apiGroups: ["aviatrix.k8s.io"]
    resources: ["aviatrixfirewalls"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["aviatrix.k8s.io"]
    resources: ["aviatrixfirewalls/status"]
    verbs: ["get", "update", "patch"]
  - apiGroups: ["aviatrix.k8s.io"]
    resources: ["aviatrixfirewalls/finalizers"]
    verbs: ["update"]
  - apiGroups: ["aviatrix.k8s.io"]
    resources: ["aviatrixnetworkdomains"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["aviatrix.k8s.io"]
    resources: ["aviatrixnetworkdomains/status"]
    verbs: ["get", "update", "patch"]
  - apiGroups: ["aviatrix.k8s.io"]
    resources: ["aviatrixnetworkdomains/finalizers"]
    verbs: ["update"]
  - apiGroups: ["aviatrix.k8s.io"]
    resources: ["aviatrixsegmentationsecuritydomains"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["aviatrix.k8s.io"]
    resources: ["aviatrixsegmentationsecuritydomains/status"]
    verbs: ["get", "update", "patch"]
  - apiGroups: ["aviatrix.k8s.io"]
    resources: ["aviatrixsegmentationsecuritydomains/finalizers"]
    verbs: ["update"]
  - apiGroups: ["aviatrix.k8s.io"]
    resources: ["aviatrixmicrosegpolicies"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["aviatrix.k8s.io"]
    resources: ["aviatrixmicrosegpolicies/status"]
    verbs: ["get", "update", "patch"]
  - apiGroups: ["aviatrix.k8s.io"]
    resources: ["aviatrixmicrosegpolicies/finalizers"]
    verbs: ["update"]
  - apiGroups: ["aviatrix.k8s.io"]
    resources: ["aviatrixedgegateways"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["aviatrix.k8s.io"]
    resources: ["aviatrixedgegateways/status"]
    verbs: ["get", "update", "patch"]
  - apiGroups: ["aviatrix.k8s.io"]
    resources: ["aviatrixedgegateways/finalizers"]
    verbs: ["update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: aviatrix-operator-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: aviatrix-operator-manager-role
subjects:
  - kind: ServiceAccount
    name: aviatrix-operator
    namespace: aviatrix-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: aviatrix-operator-leader-election-rolebinding
  namespace: aviatrix-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: aviatrix-operator-leader-election-role
subjects:
  - kind: ServiceAccount
    name: aviatrix-operator
    namespace: aviatrix-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: aviatrix-operator-leader-election-role
  namespace: aviatrix-system
rules:
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]